# Description
# ===========
# This workflow is triggered each time
# commits are pushed to GitHub or a pull request is opened.
# It launches three jobs in parallel : a build with java 8,
# a build with java 11 and a SonarCloud analysis.
---
name: Stats generation

on: [workflow_dispatch, create]

jobs:

  build:
    runs-on: ubuntu-22.04
    name: Stats for cnes report
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: |
          pip install requests tabulate
          echo "# Downloads for sonar-cnes-report" > stats.md
          python ci_tools/stats_dl.py >> stats.md
          cat stats.md
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'stats.md'
          author_name: CNES_BOT

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: CNES_BOT@donot.reply

          message: 'Updates cnes report download stats'

    
